### ISSUE TITLE
Use common package structure

### ISSUE THREAD

**Issue by JohnKhandygo** [SergeyChernonog/XORcipher#2]
В java проектах принято файлы исходного кода организовать в определнной структуре папок. Описание одного из наиболее распространенных способов организации проекта смотри [здесь](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) или [здесь](https://stackoverflow.com/questions/41638654/java-project-folder-structure-in-intellij-idea). 

Кроме того, в java принято орагнизовывать классы в пакеты. Общепринятые правила именования пакетов см. [здесь](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). Понятно, что у Вас скорее всего нет никакого сайта. В этом случае можно его придумать или взять название орагнизации, в рамках которой делается проект. Например, `org.spbstu.your_surname`.

Каждый файл исходного кода должен находится в структуре папок, соответствующей названию его пакета. Например, если файл исходного кода озаглавлен директивой `package com.mycompany.myname`, то этот файл должен располагаться по пути `com/mycompany/myname` относительно папки с исходным кодом внутри проекта.  

В maven проектах принято использовать `groupId` в качестве префикса для всех пакетов проекта. Соответственно, к `groupId` применяются все те же правила именования, что и к пакетам.

**Comment by JohnKhandygo** [comment]
При импорте проекта в идею он некорректно собирается. Вам необходимо поправить pom.xml следующим образом:
```
<sourceDirectory>src/main/java</sourceDirectory>
<testSourceDirectory>src/test/java</testSourceDirectory>
```

**Comment by SergWh** [comment]
Не пришли оповещения на почту.
Исправил замечания по поводу тестов и pom.xml
